# Generic configuration to be applied to all services
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

#H2 configuration
spring:
  h2:
    console:
      enabled: true
  cloud:
    refresh:
      enabled: false
