management:
endpoint:
 metrics:
  enabled: true
prometheus:
 enabled: true
endpoints:
 web:
  exposure:
   include: "*"
metrics:
 export:
  prometheus:
   enabled: true
spring:
 h2:
  console:
   enabled: true
 cloud:
  refresh:
   enabled: false
 profiles:
  active: local
product:
 url: http://localhost:8090
feign:
  hystrix:
    enabled: false
  client:
    default:
      connect-timeout: 10000
      read-timeout: 10000 

  
